// Auto-generated by build.rs. Do not edit by hand.
pub const WIDTH: u32 = 800;
pub const HEIGHT: u32 = 800;
pub const TITLE: &str = "Perlin Flow Particles";
pub const SCALE: f32 = 0.004_f32;
pub const Z: f32 = 0_f32;
pub const Z_STEP: f32 = 0.004_f32;
pub const FORCE: f32 = 0.8_f32;
pub const FRICTION: f32 = 0.985_f32;
pub const STEPS_PER_FRAME: u32 = 300;
pub const SPAWN_COUNT_FACTOR: f32 = 0.25_f32;
pub const FADE: f32 = 0.03_f32;
pub const COLOR_MODE_STR: &str = "Direction";
pub const PAUSED: bool = false;
pub const NOISE_SEED: u32 = 42;
pub const RNG_SEED: u64 = 123456789;
pub const SCREENSAVER_HIDE_CURSOR: bool = true;
pub const EXIT_ARM_DELAY_MS: u32 = 500;
